spring:
  application:
    name: meeting-assistant

  datasource:
    url: jdbc:postgresql://localhost:5432/meeting_assistant
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-hEwC6GUhHQqiHO8iD647BdC1F5344aAaB44452FeA282827a}
      base-url: ${OPENAI_BASE_URL:https://aihubmix.com}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7

server:
  port: 8080

# Application specific configuration
meeting:
  audio:
    segment-duration: 3  # seconds
    max-buffer-size: 10  # number of segments
  transcription:
    batch-size: 5
  websocket:
    max-connections: 100
